FROM csp-java8:1.0
MAINTAINER Dimis

ENV JAVA_HOME=/usr/lib/jvm/default-jvm

RUN apk --update add postgresql-client

COPY vcbridge-entrypoint.sh /

EXPOSE 8080

CMD ["/bin/sh", "/vcbridge-entrypoint.sh"]

