# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_incomingdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomingdata',
            options={'ordering': ['-created'], 'verbose_name': 'Received Data', 'verbose_name_plural': 'Received Data'},
        ),
        migrations.RenameField(
            model_name='incomingdata',
            old_name='record_id',
            new_name='model_name',
        ),
        migrations.AddField(
            model_name='incomingdata',
            name='model_pk',
            field=models.TextField(default='bla'),
            preserve_default=False,
        ),
    ]
