# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('constituency_type', 'Constituency Type'), ('email_visibility', 'Email Visibility'), ('membership_state', 'Membership Status'), ('nis_sector', 'NIS Sector'), ('nis_team_type', 'NIS Team Type'), ('proactive_service', 'Proactive Service'), ('quality_management', 'Quality Management'), ('reactive_service', 'Reactive Service'), ('team_role', 'Team Role'), ('team_status', 'Team Status')], db_index=True, max_length=255)),
                ('value', models.CharField(max_length=10000)),
            ],
        ),
    ]
