# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-06 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='name',
            field=models.CharField(choices=[('constituency_type', 'Constituency Type'), ('email_visibility', 'Email Visibility'), ('membership_state', 'Membership Status'), ('nis_sector', 'NIS Sector'), ('nis_team_type', 'NIS Team Type'), ('proactive_service', 'Proactive Service'), ('quality_management', 'Quality Management'), ('reactive_service', 'Reactive Service'), ('team_role', 'Team Role'), ('team_status', 'Team Status'), ('phone_tag', 'Phone Tag'), ('phone_visibility', 'Phone Visibility'), ('key_tag', 'Key Tag'), ('key_method', 'Key Method'), ('key_visibility', 'Key Visibility')], db_index=True, max_length=255),
        ),
    ]
