# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-26 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20180306_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigKV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('remove_incoming_after_days', 'How many days to keep incoming contacts')], db_index=True, max_length=255, unique=True)),
                ('value', models.TextField()),
            ],
        ),
    ]
