# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 13:25
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personkeyorcertificate',
            name='visibility',
            field=models.CharField(choices=[('private', 'Public'), ('restricted', 'Restricted'), ('public', 'Private')], default='private', max_length=20),
        ),
        migrations.AlterField(
            model_name='teamcontact',
            name='access_of_accredited_teams',
            field=models.CharField(choices=[('', '-'), ('supported', 'Supported'), ('unsupported', 'Not Supported')], max_length=20, verbose_name="Access of accredited teams to your team's data (MUST)"),
        ),
        migrations.AlterField(
            model_name='teamcontact',
            name='adhere_to_tlp',
            field=models.CharField(choices=[('', '-'), ('supported', 'Supported'), ('unsupported', 'Not Supported')], max_length=20, verbose_name='Adhere to the Information Sharing Traffic Light Protocol (MUST)'),
        ),
        migrations.AlterField(
            model_name='teamcontact',
            name='allow_site_visits',
            field=models.CharField(choices=[('', '-'), ('supported', 'Supported'), ('unsupported', 'Not Supported')], max_length=20, verbose_name='Allow site visits of the TI service team (MUST)'),
        ),
        migrations.AlterField(
            model_name='teamcontact',
            name='allow_ti_gpg_key',
            field=models.CharField(choices=[('', '-'), ('supported', 'Supported'), ('unsupported', 'Not Supported')], max_length=20, verbose_name='Allow GPG/PGP key signatures by the TI service team (MUST)'),
        ),
        migrations.AlterField(
            model_name='teamcontact',
            name='commitment_updates',
            field=models.CharField(choices=[('', '-'), ('supported', 'Supported'), ('unsupported', 'Not Supported')], max_length=20, verbose_name='Commitment to provide regular updates for team data (MUST)'),
        ),
        migrations.AlterField(
            model_name='teamcontact',
            name='contact_postal_country',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='teamcontact',
            name='csirt_code_of_practice',
            field=models.CharField(choices=[('', '-'), ('supported', 'Supported'), ('unsupported', 'Not Supported')], max_length=20, verbose_name='Compliance with the "CSIRT Code of Practive" (SHOULD)'),
        ),
        migrations.AlterField(
            model_name='teamcontact',
            name='csp_id',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='CSP ID'),
        ),
        migrations.AlterField(
            model_name='teamcontact',
            name='external_services_rfc2350',
            field=models.CharField(choices=[('', '-'), ('supported', 'Supported'), ('unsupported', 'Not Supported')], max_length=20, verbose_name='External services described in RFC 2350 format (MUST)'),
        ),
        migrations.AlterField(
            model_name='teamcontact',
            name='meetings_attendance',
            field=models.CharField(choices=[('', '-'), ('supported', 'Supported'), ('unsupported', 'Not Supported')], max_length=20, verbose_name='Regular attendance a TF-CSIRT/TI Meetings (SHOULD)'),
        ),
        migrations.AlterField(
            model_name='teamcontact',
            name='payment_of_fees',
            field=models.CharField(choices=[('', '-'), ('supported', 'Supported'), ('unsupported', 'Not Supported')], max_length=20, verbose_name='Payment of fees for the TI service (MUST)'),
        ),
        migrations.AlterField(
            model_name='teamcontact',
            name='protect_information_received',
            field=models.CharField(choices=[('', '-'), ('supported', 'Supported'), ('unsupported', 'Not Supported')], max_length=20, verbose_name='Protect information received by your team (MUST)'),
        ),
        migrations.AlterField(
            model_name='teamcontact',
            name='provide_feedback',
            field=models.CharField(choices=[('', '-'), ('supported', 'Supported'), ('unsupported', 'Not Supported')], max_length=20, verbose_name='Provide feedback to questions of the TI service (MUST)'),
        ),
        migrations.AlterField(
            model_name='teamcontact',
            name='provide_team_description',
            field=models.CharField(choices=[('', '-'), ('supported', 'Supported'), ('unsupported', 'Not Supported')], max_length=20, verbose_name='Provide team description (MUST)'),
        ),
        migrations.AlterField(
            model_name='teamcontact',
            name='public_access',
            field=models.CharField(choices=[('', '-'), ('supported', 'Supported'), ('unsupported', 'Not Supported')], max_length=20, verbose_name="Public access to your team's data marked as public (MUST)"),
        ),
        migrations.AlterField(
            model_name='teamcontact',
            name='reaction_texts_particiation',
            field=models.CharField(choices=[('', '-'), ('supported', 'Supported'), ('unsupported', 'Not Supported')], max_length=20, verbose_name='Participation in "Reaction Tests" (SHOULD)'),
        ),
        migrations.AlterField(
            model_name='teamcontact',
            name='registration_two_teams',
            field=models.CharField(choices=[('', '-'), ('supported', 'Supported'), ('unsupported', 'Not Supported')], max_length=20, verbose_name='Registration of two team representative (SHOULD)'),
        ),
        migrations.AlterField(
            model_name='teamcontact',
            name='sim3_support',
            field=models.CharField(choices=[('', '-'), ('supported', 'Supported'), ('unsupported', 'Not Supported')], max_length=20, verbose_name='Acceptance of SIM3 Model as framework for self-assessment (SHOULD)'),
        ),
        migrations.AlterField(
            model_name='teamkeyorcertificate',
            name='visibility',
            field=models.CharField(choices=[('private', 'Public'), ('restricted', 'Restricted'), ('public', 'Private')], default='private', max_length=20),
        ),
        migrations.AlterField(
            model_name='teammemberkeyorcertificate',
            name='visibility',
            field=models.CharField(choices=[('private', 'Public'), ('restricted', 'Restricted'), ('public', 'Private')], default='private', max_length=20),
        ),
    ]
