# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 13:31
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20180202_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcontact',
            name='postal_country',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='postal_country',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None),
        ),
    ]
