# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 14:23
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20180202_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingTeamContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('csp_id', models.TextField()),
                ('app_id', models.TextField()),
                ('target_circle_id', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('target_team_id', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('data_object', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'ordering': ['created'],
                'verbose_name': 'Incoming Team Contact',
                'verbose_name_plural': 'Incoming Team Contacts',
            },
        ),
        migrations.AlterModelOptions(
            name='personmembership',
            options={'verbose_name': 'Membership', 'verbose_name_plural': 'Memberships'},
        ),
        migrations.AlterModelOptions(
            name='teammembermembership',
            options={'verbose_name': 'Membership', 'verbose_name_plural': 'Memberships'},
        ),
        migrations.AlterModelOptions(
            name='teammembership',
            options={'verbose_name': 'Membership', 'verbose_name_plural': 'Memberships'},
        ),
        migrations.AlterField(
            model_name='teammember',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
