# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20180206_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamcontact',
            old_name='established_on',
            new_name='established',
        ),
        migrations.AddField(
            model_name='teamcontact',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamcontact',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description'),
        ),
    ]
