# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-13 13:10
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20180212_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localtrustcircle',
            name='tlp',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('amber', 'Amber'), ('green', 'Green'), ('white', 'White')], max_length=255, verbose_name='TLP'),
        ),
        migrations.AlterField(
            model_name='teamcontact',
            name='constituency_asns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None, verbose_name='Consituency ASNs'),
        ),
        migrations.AlterField(
            model_name='teamcontact',
            name='constituency_domains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None, verbose_name='Consituency Domains'),
        ),
        migrations.AlterField(
            model_name='teamcontact',
            name='constituency_ipranges',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None, verbose_name='Consituency IP-Ranges'),
        ),
        migrations.AlterField(
            model_name='teamcontact',
            name='nis_sectors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None, verbose_name='NIS Sectors'),
        ),
        migrations.AlterField(
            model_name='teamcontact',
            name='nis_team_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None, verbose_name='NIS Team Types'),
        ),
        migrations.AlterField(
            model_name='teamcontact',
            name='scope_asns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None, verbose_name='Scope ASNs'),
        ),
        migrations.AlterField(
            model_name='teamcontact',
            name='scope_email',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None, verbose_name='Scope Emails'),
        ),
        migrations.AlterField(
            model_name='teamcontact',
            name='scope_ipranges',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None, verbose_name='Scope IP-ranges'),
        ),
    ]
