# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-13 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0005_auto_20180213_1310'),
        ('contacts', '0008_auto_20180213_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='localtrustcircle',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='in_localcircles', to='central.Team', verbose_name='Teams'),
        ),
    ]
