# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-01 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_localtrustcircle_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcontact',
            name='csp_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='CSP ID'),
        ),
    ]
