# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-20 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20180801_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamcontact',
            old_name='reaction_texts_particiation',
            new_name='reaction_tests_particiation',
        ),
        migrations.RenameField(
            model_name='teamcontact',
            old_name='reaction_texts_particiation_comment',
            new_name='reaction_tests_particiation_comment',
        ),
    ]
