# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-07-31 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_auto_20190731_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localtrustcircle',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
    ]
