# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-08-07 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


def forwards(apps, schema_editor):
    TeamContact = apps.get_model('contacts', 'teamcontact')
    PersonContact = apps.get_model('contacts', 'personcontact')
    LTC = apps.get_model('contacts', 'localtrustcircle')

    for team in TeamContact.objects.all():
        team.modified = team.created
        team.save()

    for p in PersonContact.objects.all():
        p.modified = p.created
        p.save()
 
    for ltc in LTC.objects.all():
        ltc.modified = ltc.created
        ltc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_auto_20190731_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='localtrustcircle',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified on'),
        ),
        migrations.AddField(
            model_name='personcontact',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personcontact',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified on'),
        ),
        migrations.AddField(
            model_name='teamcontact',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified on'),
        ),
        migrations.AlterField(
            model_name='localtrustcircle',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='in_localcircles', to='central.Team', verbose_name='CSP Teams'),
        ),

        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
