# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-08-27 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_auto_20190807_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingteamcontact',
            name='seen',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Object viewed on'),
        ),
    ]
