# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-08-30 14:12
from __future__ import unicode_literals

from django.db import migrations


def remove_csp_team_details(apps, schema_editor):
    TeamContact = apps.get_model('contacts', 'TeamContact')
    for tc in TeamContact.objects.all():
        tc.csp_id = ''
        tc.csp_domain = ''
        tc.csp_installed = False
        tc.nis_team_types = []
        tc.nis_sectors = []
        tc.status = ''
        tc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_incomingteamcontact_seen'),
    ]

    operations = [
        migrations.RunPython(remove_csp_team_details),
    ]
