# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20180202_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcontact',
            name='postal_country',
            field=models.TextField(blank=True, verbose_name='Postal Country'),
        ),
        migrations.AlterField(
            model_name='teamcontact',
            name='contact_postal_country',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='postal_country',
            field=models.TextField(blank=True, verbose_name='Postal Country'),
        ),
    ]
