# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 12:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0002_auto_20180202_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalteam',
            name='team_selfinfo',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_selfinfo',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalteam',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='team',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created on'),
        ),
    ]
