# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-13 13:10
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0004_auto_20180213_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalteam',
            name='nis_sectors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None, verbose_name='NIS Sectors'),
        ),
        migrations.AlterField(
            model_name='historicalteam',
            name='nis_team_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None, verbose_name='NIS Team Types'),
        ),
        migrations.AlterField(
            model_name='historicaltrustcircle',
            name='tlp',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('amber', 'Amber'), ('green', 'Green'), ('white', 'White')], default='', max_length=255, verbose_name='TLP'),
        ),
        migrations.AlterField(
            model_name='team',
            name='nis_sectors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None, verbose_name='NIS Sectors'),
        ),
        migrations.AlterField(
            model_name='team',
            name='nis_team_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None, verbose_name='NIS Team Types'),
        ),
        migrations.AlterField(
            model_name='trustcircle',
            name='tlp',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('amber', 'Amber'), ('green', 'Green'), ('white', 'White')], default='', max_length=255, verbose_name='TLP'),
        ),
    ]
