# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-13 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0003_auto_20180212_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrustcircle',
            name='tlp',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('amber', 'Amber'), ('green', 'Green'), ('white', 'White')], max_length=255),
        ),
        migrations.AddField(
            model_name='trustcircle',
            name='tlp',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('amber', 'Amber'), ('green', 'Green'), ('white', 'White')], max_length=255),
        ),
    ]
