# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-07-31 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0006_auto_20190731_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltrustcircle',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='trustcircle',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
