# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[(b'create', b'Create'), (b'update', b'Update'), (b'delete', b'Delete')], max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('model_pk', models.CharField(max_length=128)),
                ('to_share', models.BooleanField(default=True)),
                ('target_trustcircle', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
