# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 17:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('csp_id', models.TextField()),
                ('app_id', models.TextField()),
                ('target_circle_id', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('target_team_id', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('record_id', models.TextField()),
                ('data_type', models.TextField()),
                ('data_object', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'verbose_name': 'Received Data',
                'verbose_name_plural': 'Received Data',
            },
        ),
    ]
