# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_auto_20180202_1804'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IncomingData',
        ),
    ]
