# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 12:34
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


def listify_target_trustcircles(apps, schema):
    ChangeLog = apps.get_model('integration', 'ChangeLog')
    for log in ChangeLog.objects.all():
        log.target_trustcircles = []
        if log.target_trustcircle:
            log.target_trustcircles = [log.target_trustcircles]
        log.save()


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0004_delete_incomingdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='target_trustcircles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, size=None),
        ),
        migrations.RunPython(listify_target_trustcircles)
    ]
