# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0005_changelog_target_trustcircles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changelog',
            name='target_trustcircle',
        ),
    ]
