# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 12:56
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0007_auto_20180208_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='target_trustcircles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=None, null=True, size=None),
        ),
    ]
