# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-05 16:08
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0008_auto_20180212_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='target_teams',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=None, null=True, size=None),
        ),
    ]
